import { dirname, extname, relative } from 'node:path';
import type { ResponseKind } from '../models/response-kind';
import type { ResponseWrapperDetection } from '../models/response-wrapper-detection';

interface ClientDeclarationSource {
  name: string;
  sourceFile: string;
  methods: readonly { name: string; responseKind?: ResponseKind }[];
}

const REMOTE_RESULT_HELPERS: Record<ResponseKind, string> = {
  json: 'RemoteResult',
  observable: 'RemoteObservableResult',
  stream: 'RemoteStreamResult',
};

const WRAPPED_RESULT_HELPER = '__NestBridgeWrapped';

const toPosixPath = (filePath: string) => filePath.replace(/\\/g, '/');

const importSpecifierFor = (sourceFile: string, outputFilePath: string) => {
  if (
    !sourceFile.startsWith('.') &&
    !/^[A-Za-z]:[\\/]/.test(sourceFile) &&
    !sourceFile.startsWith('/')
  ) {
    return sourceFile;
  }

  const relativePath = toPosixPath(relative(dirname(outputFilePath), sourceFile));
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
};

const stripExtension = (filePath: string) => {
  const extension = extname(filePath);
  return extension.length > 0 ? filePath.slice(0, -extension.length) : filePath;
};

export const generateControllerDeclaration = (
  controller: ClientDeclarationSource,
  outputFilePath: string,
  responseWrapper?: ResponseWrapperDetection,
): string => {
  const sourceFileSpecifier = importSpecifierFor(controller.sourceFile, outputFilePath);
  const importSpecifier = stripExtension(sourceFileSpecifier);
  const serverAlias = `__Server${controller.name}`;

  const helperNameFor = (method: ClientDeclarationSource['methods'][number]) =>
    responseWrapper !== undefined && (method.responseKind ?? 'json') === 'json'
      ? WRAPPED_RESULT_HELPER
      : REMOTE_RESULT_HELPERS[method.responseKind ?? 'json'];

  const methodDeclarations = controller.methods.map((method) => {
    const helperName = helperNameFor(method);
    return `  ${method.name}(...args: Parameters<${serverAlias}['${method.name}']>): ${helperName}<${serverAlias}['${method.name}']>;`;
  });

  const classBody = ['  constructor();', '', ...methodDeclarations].join('\n');

  const rawHelperNames = controller.methods.map((method) => helperNameFor(method));
  const hasWrappedMethod = rawHelperNames.includes(WRAPPED_RESULT_HELPER);
  const helperImports =
    rawHelperNames.length === 0
      ? ['RemoteResult']
      : Array.from(new Set(rawHelperNames.filter((name) => name !== WRAPPED_RESULT_HELPER))).sort();

  const wrappedResultTypeAliasLines =
    responseWrapper !== undefined && hasWrappedMethod
      ? [
          `type ${WRAPPED_RESULT_HELPER}<T> = T extends (...args: never[]) => infer Result ? Promise<${responseWrapper.wrappedResultTypeSource}> : never;`,
          '',
        ]
      : [];

  return [
    `import type { ${controller.name} as ${serverAlias} } from '${importSpecifier}';`,
    ...(helperImports.length > 0
      ? [`import type { ${helperImports.join(', ')} } from 'nestbridge';`]
      : []),
    '',
    '/**',
    ' * Generated by NestBridge — client-facing methods only.',
    ` * @see {@link ${sourceFileSpecifier}} for the real controller implementation.`,
    ' */',
    ...wrappedResultTypeAliasLines,
    `export declare class ${controller.name} {`,
    classBody,
    '}',
    '',
  ].join('\n');
};
