export const ERROR_BODY_TYPE_NAME = 'NestBridgeErrorBody';

export const generateErrorBodyDeclaration = (errorBodyTypeSource: string): string =>
  [
    '/**',
    " * Generated by NestBridge — inferred shape of the global exception filter's response body.",
    ' */',
    `export type ${ERROR_BODY_TYPE_NAME} = ${errorBodyTypeSource};`,
    '',
  ].join('\n');
