import { dirname, extname, relative } from 'node:path';
import type { ControllerDefinition } from '../models';

const toPosixPath = (filePath: string) => filePath.replace(/\\/g, '/');

const importSpecifierFor = (sourceFile: string, outputFilePath: string) => {
  if (
    !sourceFile.startsWith('.') &&
    !/^[A-Za-z]:[\\/]/.test(sourceFile) &&
    !sourceFile.startsWith('/')
  ) {
    return sourceFile;
  }

  const relativePath = toPosixPath(relative(dirname(outputFilePath), sourceFile));
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
};

const stripExtension = (filePath: string) => {
  const extension = extname(filePath);
  return extension.length > 0 ? filePath.slice(0, -extension.length) : filePath;
};

export const generateControllerDeclaration = (
  controller: ControllerDefinition,
  outputFilePath: string,
) => {
  const sourceFileSpecifier = importSpecifierFor(controller.sourceFile, outputFilePath);
  const importSpecifier = stripExtension(sourceFileSpecifier);
  const serverAlias = `__Server${controller.name}`;
  const methodDeclarations = controller.methods.map(
    (method) => `  ${method.name}: RemoteMethod<${serverAlias}['${method.name}']>;`,
  );

  const classBody = ['  constructor();', '', ...methodDeclarations].join('\n');

  return [
    `import type { ${controller.name} as ${serverAlias} } from '${importSpecifier}';`,
    `import type { RemoteMethod } from '@nestbridge/runtime';`,
    '',
    '/**',
    ' * Generated by NestBridge — client-facing methods only.',
    ` * @see {@link ${sourceFileSpecifier}} for the real controller implementation.`,
    ' */',
    `export declare class ${controller.name} {`,
    classBody,
    '}',
    '',
  ].join('\n');
};
