import { dirname, extname, relative } from 'node:path';
import type { ResponseKind } from '../models/response-kind';

interface ClientDeclarationSource {
  name: string;
  sourceFile: string;
  methods: readonly { name: string; responseKind?: ResponseKind }[];
}

const REMOTE_RESULT_HELPERS: Record<ResponseKind, string> = {
  json: 'RemoteResult',
  observable: 'RemoteObservableResult',
  stream: 'RemoteStreamResult',
};

const toPosixPath = (filePath: string) => filePath.replace(/\\/g, '/');

const importSpecifierFor = (sourceFile: string, outputFilePath: string) => {
  if (
    !sourceFile.startsWith('.') &&
    !/^[A-Za-z]:[\\/]/.test(sourceFile) &&
    !sourceFile.startsWith('/')
  ) {
    return sourceFile;
  }

  const relativePath = toPosixPath(relative(dirname(outputFilePath), sourceFile));
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
};

const stripExtension = (filePath: string) => {
  const extension = extname(filePath);
  return extension.length > 0 ? filePath.slice(0, -extension.length) : filePath;
};

export const generateControllerDeclaration = (
  controller: ClientDeclarationSource,
  outputFilePath: string,
) => {
  const sourceFileSpecifier = importSpecifierFor(controller.sourceFile, outputFilePath);
  const importSpecifier = stripExtension(sourceFileSpecifier);
  const serverAlias = `__Server${controller.name}`;
  const methodDeclarations = controller.methods.map((method) => {
    const helperName = REMOTE_RESULT_HELPERS[method.responseKind ?? 'json'];
    return `  ${method.name}(...args: Parameters<${serverAlias}['${method.name}']>): ${helperName}<${serverAlias}['${method.name}']>;`;
  });

  const classBody = ['  constructor();', '', ...methodDeclarations].join('\n');

  const usedHelperNames = new Set(
    controller.methods.map((method) => REMOTE_RESULT_HELPERS[method.responseKind ?? 'json']),
  );
  const helperImports = Array.from(
    usedHelperNames.size > 0 ? usedHelperNames : ['RemoteResult'],
  ).sort();

  return [
    `import type { ${controller.name} as ${serverAlias} } from '${importSpecifier}';`,
    `import type { ${helperImports.join(', ')} } from '@nestbridge/runtime';`,
    '',
    '/**',
    ' * Generated by NestBridge — client-facing methods only.',
    ` * @see {@link ${sourceFileSpecifier}} for the real controller implementation.`,
    ' */',
    `export declare class ${controller.name} {`,
    classBody,
    '}',
    '',
  ].join('\n');
};
