import { describe, expect, it } from 'vitest';
import { generateErrorBodyDeclaration } from '../src/declarations';

describe('generateErrorBodyDeclaration', () => {
  it('emits a NestBridgeErrorBody type alias built from the detected error body shape', () => {
    const declaration = generateErrorBodyDeclaration('{ statusCode: number; message: string }');

    expect(declaration).toContain(
      'export type NestBridgeErrorBody = { statusCode: number; message: string };',
    );
  });

  it('links back to NestBridge in a header comment', () => {
    const declaration = generateErrorBodyDeclaration('{ message: string }');

    expect(declaration).toContain('Generated by NestBridge');
  });
});
